version: "3.8"
services:
  alinspace-web:
    build: AlinSpace.Web/
  alinspace-web-reverseproxy:
    build: AlinSpace.Web.ReverseProxy/
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/archive/$DOMAIN/:/etc/nginx/certs/	
